# ===============================================================
# CONFIGURATION GÉNÉRALE
# ===============================================================
spring.application.name=vigilance
server.port=8080

# ===============================================================
# BASE DE DONNÉES (POSTGRESQL)
# ===============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/vigilance
spring.datasource.username=postgres
spring.datasource.password=Lovanirina#3
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================================================
# MOTEUR DE VUE (JSP)
# ===============================================================
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# ===============================================================
# ENVOI D'EMAILS (GMAIL SMTP)
# ===============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ramarolahycarlo11@gmail.com
spring.mail.password=pfrhzlampcbjepen
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================================================
# SMS (TWILIO)
# ===============================================================
twilio.account.sid=TON_SID_ICI
twilio.auth.token=TON_TOKEN_ICI
twilio.phone.number=+14786660839

# ===============================================================
# SÉCURITÉ ET LOGS
# ===============================================================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=INFO